// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/svandecappelle/gitcontrib/pkg/swagger/server/models"
)

// GetAPIReportOKCode is the HTTP code returned for type GetAPIReportOK
const GetAPIReportOKCode int = 200

/*
GetAPIReportOK Returns the report of a given day

swagger:response getApiReportOK
*/
type GetAPIReportOK struct {

	/*
	  In: Body
	*/
	Payload *models.GitStatisticsReport `json:"body,omitempty"`
}

// NewGetAPIReportOK creates GetAPIReportOK with default headers values
func NewGetAPIReportOK() *GetAPIReportOK {

	return &GetAPIReportOK{}
}

// WithPayload adds the payload to the get Api report o k response
func (o *GetAPIReportOK) WithPayload(payload *models.GitStatisticsReport) *GetAPIReportOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api report o k response
func (o *GetAPIReportOK) SetPayload(payload *models.GitStatisticsReport) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIReportNotFoundCode is the HTTP code returned for type GetAPIReportNotFound
const GetAPIReportNotFoundCode int = 404

/*
GetAPIReportNotFound Not any reports found

swagger:response getApiReportNotFound
*/
type GetAPIReportNotFound struct {
}

// NewGetAPIReportNotFound creates GetAPIReportNotFound with default headers values
func NewGetAPIReportNotFound() *GetAPIReportNotFound {

	return &GetAPIReportNotFound{}
}

// WriteResponse to the client
func (o *GetAPIReportNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
