// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPIReportHandlerFunc turns a function with the right signature into a get API report handler
type GetAPIReportHandlerFunc func(GetAPIReportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIReportHandlerFunc) Handle(params GetAPIReportParams) middleware.Responder {
	return fn(params)
}

// GetAPIReportHandler interface for that can handle valid get API report params
type GetAPIReportHandler interface {
	Handle(GetAPIReportParams) middleware.Responder
}

// NewGetAPIReport creates a new http.Handler for the get API report operation
func NewGetAPIReport(ctx *middleware.Context, handler GetAPIReportHandler) *GetAPIReport {
	return &GetAPIReport{Context: ctx, Handler: handler}
}

/*
	GetAPIReport swagger:route GET /api/report getApiReport

Get statistics report for given dates
*/
type GetAPIReport struct {
	Context *middleware.Context
	Handler GetAPIReportHandler
}

func (o *GetAPIReport) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIReportParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
