// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GitStatisticsReport git statistics report
//
// swagger:model GitStatisticsReport
type GitStatisticsReport struct {

	// commits
	Commits []*GitCommits `json:"commits"`

	// date from
	// Format: date-time
	DateFrom strfmt.DateTime `json:"dateFrom,omitempty"`

	// date to
	// Format: date-time
	DateTo strfmt.DateTime `json:"dateTo,omitempty"`
}

// Validate validates this git statistics report
func (m *GitStatisticsReport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommits(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDateFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDateTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GitStatisticsReport) validateCommits(formats strfmt.Registry) error {
	if swag.IsZero(m.Commits) { // not required
		return nil
	}

	for i := 0; i < len(m.Commits); i++ {
		if swag.IsZero(m.Commits[i]) { // not required
			continue
		}

		if m.Commits[i] != nil {
			if err := m.Commits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("commits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("commits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GitStatisticsReport) validateDateFrom(formats strfmt.Registry) error {
	if swag.IsZero(m.DateFrom) { // not required
		return nil
	}

	if err := validate.FormatOf("dateFrom", "body", "date-time", m.DateFrom.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GitStatisticsReport) validateDateTo(formats strfmt.Registry) error {
	if swag.IsZero(m.DateTo) { // not required
		return nil
	}

	if err := validate.FormatOf("dateTo", "body", "date-time", m.DateTo.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this git statistics report based on the context it is used
func (m *GitStatisticsReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCommits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GitStatisticsReport) contextValidateCommits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Commits); i++ {

		if m.Commits[i] != nil {
			if err := m.Commits[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("commits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("commits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GitStatisticsReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GitStatisticsReport) UnmarshalBinary(b []byte) error {
	var res GitStatisticsReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
