// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GitAuthorContributions git author contributions
//
// swagger:model GitAuthorContributions
type GitAuthorContributions struct {

	// additions
	Additions int64 `json:"additions,omitempty"`

	// deletions
	Deletions int64 `json:"deletions,omitempty"`
}

// Validate validates this git author contributions
func (m *GitAuthorContributions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this git author contributions based on context it is used
func (m *GitAuthorContributions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GitAuthorContributions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GitAuthorContributions) UnmarshalBinary(b []byte) error {
	var res GitAuthorContributions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
